name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Give the workflow explicit permission to write repository contents so the
# deployment action can push the `gh-pages` branch using the provided token.
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # ensure the checkout action keeps credentials so the deploy step can push
          persist-credentials: true
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
